### ISSUE TITLE
Set maximum supply temperature

### ISSUE THREAD

**Issue by theelog** [Laxilef/OTGateway#2]
Is there a way to control the maximum central heating supply temperature.

It might be an artificial cap on the heating setpoint.
All commercially available thermostats have this feature.

OpenTherm documentatio v.2.2 states this:
`The master decides the actual range over which the control setpoint is defined. The default range is
assumed to be 0 to 100.`

I think I found it in the Settings.h, `heatingMaxTemp` (currently set to 90).

It would be perfect if it were able to be set using Home Assistant.

**Comment by Laxilef** [comment]
The controller tries to get the min and max heating temperature from the boiler, if it supports it
https://github.com/Laxilef/OTGateway/blob/3cafcde58c21fbfbba2f645143a325f814e402b8/src/OpenThermTask.h#L319

In variables "vars.parameters.heatingMinTemp" & "vars.parameters.heatingMaxTemp" values by default

**Comment by theelog** [comment]
Is the retrieved max reported somewhere?

**Comment by Laxilef** [comment]
Via mqtt explorer
![Screenshot_1](https://github.com/Laxilef/OTGateway/assets/34578544/b16ac9fe-a2fe-4e80-aad5-19b782f56cb0)

**Comment by Laxilef** [comment]
Maybe later add entities to HA

**Comment by theelog** [comment]
Nice, that's even better. I knew I've configured it in the furnace menu at one time.
<img width="229" alt="image" src="https://github.com/Laxilef/OTGateway/assets/2011325/a04db336-18f5-43ce-9266-3290116b8044">

Just sharing a quick way to get it into Home Assistant:
```
mqtt:
  sensor:
    - unique_id: opentherm_heating_max_temp
      name: Opentherm Heating Max Temp
      state_topic: "opentherm/state"
      value_template: "{{ value_json.parameters.heatingMaxTemp }}"
      device_class: temperature
      unit_of_measurement: "%C"
```
