### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by Balaganoff** [Laxilef/OTGateway#7]
1. Какая логика в подключении датчиков,
  - Экспериментально я выяснил так:
  **External** - это датчик непосредственно подключенный к ESP
  **Boiler**  - ??
  **Manual**  - это внешний датчик, привязываемый через автоматизацию Home Assistant.  Не совсем понят смыл ручной регулировки. Зачем это сделано? Ведь при просмотре со смартфона можно нечаянно установить неверную температуру и нарушить логику работы.

Я правильно понял или где-то можно подробнее прочитать?

**Comment by Laxilef** [comment]
External - внешний DS18B20 или аналог, который физически подключен
Boiler - съем с котла по opentherm. Некоторые котлы позволяют подключать датчик внешней температуры или имеют датчик на приточке
Manual - для передачи температуры контроллеру через автоматизацию, например с zigbee датчика,  который висит на улице
Сбить можно,  но автоматизация должна потом все равно установить реальную температуру

**Comment by Balaganoff** [comment]
> Manual - для передачи температуры контроллеру через автоматизацию, например с zigbee датчика, который висит на улице
> Сбить можно, но автоматизация должна потом все равно установить реальную температуру.

А зачем это это реализовано ? Если все равно установится реальная температура. Мое - мнение ручная регулировка лишняя и вводит в заблуждение.

**Comment by Balaganoff** [comment]
Шаг изменения температуры отопления в 1градус - это слишком грубо. Порог температурной чувствительности человека по разным источникам считается 0.2-0.4 градуса. Измерять мы можем с точностью 0.1. Почему-бы не использовать эту возможность?

В аналогичных теморегуляторах устанавливается с точностью от 0.1 до 0.5 градуса. (зависит от производителя)

**Comment by Balaganoff** [comment]
Есть какой-то канал общения кроме гитхаба ? Форум или телеграмм ?

**Comment by Laxilef** [comment]
@Balaganoff, пока только тут и на [форуме baxi](https://forum.baxi.ru/viewtopic.php?p=80598)

**Comment by bigbrother72** [comment]
> Для climate.opentherm_heating установлен шаг 0.5 градуса.

пытался поменять в publishClimateHeating()

    doc[F("temp_step")] = 0.1;
    doc[F("target_temp_step")] = 0.1;

Не  помогает.

**Comment by Balaganoff** [comment]
> Не помогает. Только на один градус шаг регулировки. А мне например 21 градус холодно, а 22 градуса уже жарко

Я для себя нашел выход - через автоматизаию пихаю нужное значение в number.opentherm_heating_target - тогда воспринимает половину градуса и работает по этому значению. Правда на карточке объекта округляет.
Вот пример установки 24.5 и ночной 22. ( такие высокие значения т.к. датчик пока стоит у котла)
![изображение](https://github.com/Laxilef/OTGateway/assets/26416834/5a544ba8-a331-41ac-a48b-d71fd5a65976)

**Comment by RYZHOP** [comment]
А можешь скинуть файл .yaml со всеми настроенными датчиками.

**Comment by Laxilef** [comment]
Попробуйте [mini-climate-card](https://github.com/artem-sedykh/mini-climate-card), через HACS ставится.
Конфиг:
```yaml
type: custom:mini-climate
entity: climate.opentherm_heating
target_temperature:
  step: 0.5
secondary_info:
  type: hvac-action
fan_mode:
  hide: true
hvac_mode:
  hide: true
  source:
    heat:
      name: Включено
    'off':
      name: Выключено
buttons:
  boost:
    icon: mdi:rocket-launch-outline
    location: bottom
    state:
      attribute: preset_mode
      mapper: 'state => (state == ''boost'' ? ''on'': ''off'')'
    toggle_action: >
      (state, climate_entity) => this.call_service('climate', 'set_preset_mode',
      { entity_id: climate_entity.entity_id, preset_mode:
      (this.toggle_state(state) == 'on' ? 'boost' : 'none') })
  heat:
    icon: mdi:power
    location: bottom
    state:
      mapper: 'state => (state == ''heat'' ? ''on'': ''off'')'
    toggle_action: >
      (state, entity, climate_entity) => this.call_service('climate',
      'set_hvac_mode', { entity_id: climate_entity.entity_id, hvac_mode:
      (this.toggle_state(state) == 'on' ? 'heat' : 'off') })

```
